### ISSUE TITLE
Support segmented button style toolbar

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/Preferences#2]
I don't always have time to do nice icons and would like to use this style:

![image](https://user-images.githubusercontent.com/170270/42094444-09d48b6a-7bda-11e8-9d31-8c324a2a844c.png)

Note how it's segmented controls in a narrow window toolbar.

`NSTabView` actually has a [style for this](https://developer.apple.com/documentation/appkit/nstabviewcontroller/tabstyle/segmentedcontrolontop) (which is also the default), but the segmented controls ends up in the window and not in the toolbar, like this:

<img width="592" alt="screen shot 2018-06-29 at 20 26 38" src="https://user-images.githubusercontent.com/170270/42094690-c1ed498a-7bda-11e8-8a34-3f6c4829d160.png">

**Help appreciated 🙌**

The only solution I can think of is to hide the `NSTabView` tabs, put an `NSSegmentedControl` centered in an `NSToolbar`, listen to when the active segment changes, and then forward that to the `NSTabView`. That is way more complicated than it should, so I'm hoping for someone to propose a better solution.

**Comment by DivineDominion** [comment]
Over at https://github.com/phranck/CCNPreferencesWindowController the segmented control is the view of a single toolbar item. You have to tweak callbacks a lot between both modes, of course, since now the segmented control is responsible for action triggers.

**Comment by phranck** [comment]
@DivineDominion Hey Christian, thanks for mentioning! 😊 I just sent out an email regarding your last contact.

I would appreciate it to see the work of my control merged into this fresh and Swift only project, because it seems to have all the functionality which is missing here at the moment. So, @sindresorhus if you have time (and agree with my suggestion) please feel free to port my _legacy_ ObjC code into your project. And if I'm not wrong, Christian should already have done some of that.

**Comment by DivineDominion** [comment]
Yeah I'm totally willing to coordinate efforts shortly, @sindresorhus, and then ship this with your library.

**Comment by phranck** [comment]
Great! If it's done and/or if it's in a state of _work in progress_ I will mark my repository as _"No longer maintained"_.

**Comment by sindresorhus** [comment]
@DivineDominion Great, PR welcome :)
