### ISSUE TITLE
Support for Touch Bar?

### ISSUE THREAD

**Issue by Hengyu** [sindresorhus/Preferences#87]
Hey team,

Do we have plan to support for Touch Bar? E.g., The Touch Bar segmented item could let you switch among preference panes.

**Comment by sindresorhus** [comment]
No plans. [The Touch Bar is dead.](https://www.digitaltrends.com/computing/why-apple-finally-killed-the-touch-bar-in-macbook-pro/) Even if it weren't, I wouldn't bother to support it personally.

**Comment by ShikiSuen** [comment]
Although I don't think the Touch Bar is killed by Apple (otherwise it shouldn't be appeared in 13-inch M2 MacBook Pro)...
... I do think it is not wise anymore to address Touch Bar support.

When Apple doesn't provide certain API, it will take a lot of work dealing with private APIs communicating with the Touch Bar. These API may be changed as the macOS evolves.
